//@version=5

strategy("Strategy name", overlay = true, initial_capital = 5000, default_qty_value = 100, process_orders_on_close=true, calc_on_every_tick=true)

timePeriod = time >= timestamp(syminfo.timezone, 2021, 12, 15, 0, 0)

movingAverage = ta.sma(close, 8)
movingAverage2 = ta.sma(close, 80)

//1 candle com máxima acima das máximas dos 2 últimos candles
isAboveLast2Candles = high[1] > high[2] and high[1] > high[3]
//2 Candle negativo
isShort = open[1] > close[1]
//close de candle abaixo das 2 medias
belowMA = close[1] < movingAverage and close[1] < movingAverage2
//subir 1, descer -1


 
//if everything is guchi = give me money
if  isAboveLast2Candles and timePeriod and isShort 
    strategy.entry("short", strategy.short)
strategy.close(id="short")

plot(movingAverage)
plot(movingAverage2)